FROM ruby:2.7.2-slim
RUN apt-get update -qq && apt-get install -y build-essential

ENV APP_HOME /backend
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install

COPY . .

EXPOSE 9292

CMD ["bundle", "exec", "puma",  "--config", "./puma.rb"]